name: Build and deploy Node.js app to Azure Web App - querymanagement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5ECCCDE96C15445B98B35090024FFE5A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4F9EEA1A1A641AE98B15C4DC09E394F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A973B3F037844D3A8C2B9EC68DAF2D37 }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'querymanagement'
          slot-name: 'Production'
          package: .
